ALTER TABLE crop_listings MODIFY COLUMN category VARCHAR(100) NOT NULL DEFAULT 'other';
ALTER TABLE crop_listings MODIFY COLUMN unit VARCHAR(30) NOT NULL DEFAULT 'kg';
ALTER TABLE equipment MODIFY COLUMN type VARCHAR(100) NOT NULL;
ALTER TABLE vehicles MODIFY COLUMN vehicle_type VARCHAR(100) NOT NULL DEFAULT 'truck';
ALTER TABLE government_notices MODIFY COLUMN category VARCHAR(100) NOT NULL DEFAULT 'notice';
