export const endpoints = {
  auth: '/auth',
  uploads: '/uploads',
  dashboard: '/dashboard',
  conversations: '/conversations',
  messages: '/messages',
  transactions: '/transactions',
  adminTransactions: '/admin/transactions',
  cropListings: '/crop-listings',
  bids: '/bids',
  orders: '/orders',
  equipment: '/equipment',
  equipmentBookings: '/equipment-bookings',
  vehicles: '/vehicles',
  transportBookings: '/transport-bookings',
  notifications: '/notifications',
  stories: '/stories',
  notices: '/government-notices',
  marketPrices: '/market-prices',
  products: '/products',
  settings: '/app-settings'
};
